[build]
  publish = "docs"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "*.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/Build/*.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]
  for = "*.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"
